spring:
  application:
    name: parking
  jackson:
    serialization.indent_output: true
    serialization.write_dates_as_timestamps: false
    serialization.write_date_timestamps_as_nanoseconds: false
    deserialization.read_date_timestamps_as_nanoseconds: false
    mapper.accept_case_insensitive_enums: true
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: true
    changelog: classpath:liquibase/changelog-master.yml
    default-schema: ${database.default_schema}
  profiles:
    active: local
  server:
    port: 8080
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  endpoint:
    health:
      show-details: always

database:
  default_schema: parking